<?php 
/** 
 * @file SQLUsuario.php 
 *  
 * Consultas SQL de la Tabla Usuario 
 * 
 * @author UNM 
 * @version V 0.1 
 * @date 08/12/2021
 *  
*/ 
class SQLUsuario 
{ 
  const AGREGAR_USUARIO = "INSERT INTO Usuario (IDUSUARIO, IDROL, Edo_idEdoRegistro, idPersona, CUENTAUSUARIO, CONTRASENAUSUARIO, FECCREACION, PREGSECRETA, RESPPREGSECRETA) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ";

  const ACTUALIZAR_USUARIO = "UPDATE Usuario SET IDUSUARIO = ?, IDROL = ?, Edo_idEdoRegistro = ?, idPersona = ?, CUENTAUSUARIO = ?, CONTRASENAUSUARIO = ?, FECCREACION = ?, PREGSECRETA = ?, RESPPREGSECRETA = ? WHERE idUsuario = ?";

  const ELIMINAR_USUARIO = "DELETE FROM Usuario WHERE idUsuario = ?";

  const CONSULTAR_USUARIO = "SELECT * FROM Usuario ORDER BY IDUSUARIO";

  const CONSULTAR_USUARIO_POR_IDUSUARIOUSUARIO = "SELECT * FROM Usuario WHERE IDUSUARIOUsuario = ?";

  const CONSULTAR_USUARIO_POR_IDROL = "SELECT * FROM Usuario WHERE IDROLUsuario = ?";

  const CONSULTAR_USUARIO_POR_EDO_IDEDOREGISTRO = "SELECT * FROM Usuario WHERE Edo_idEdoRegistroUsuario = ?";

  const CONSULTAR_USUARIO_POR_IDPERSONA = "SELECT * FROM Usuario WHERE idPersonaUsuario = ?";

  const CONSULTAR_USUARIO_POR_CUENTAUSUARIO = "SELECT * FROM Usuario WHERE UPPER(CUENTAUSUARIOUsuario) = UPPER(?)";

  const CONSULTAR_USUARIO_POR_CUENTAUSUARIO_APROX = "SELECT * FROM Usuario WHERE UPPER(CUENTAUSUARIOUsuario) LIKE UPPER(?) ORDER BY CUENTAUSUARIOUsuario";

  const CONSULTAR_USUARIO_POR_CONTRASENAUSUARIO = "SELECT * FROM Usuario WHERE UPPER(CONTRASENAUSUARIOUsuario) = UPPER(?)";

  const CONSULTAR_USUARIO_POR_CONTRASENAUSUARIO_APROX = "SELECT * FROM Usuario WHERE UPPER(CONTRASENAUSUARIOUsuario) LIKE UPPER(?) ORDER BY CONTRASENAUSUARIOUsuario";

  const CONSULTAR_USUARIO_POR_FECCREACION = "SELECT * FROM Usuario WHERE FECCREACIONUsuario = ?";

  const CONSULTAR_USUARIO_POR_PREGSECRETA = "SELECT * FROM Usuario WHERE UPPER(PREGSECRETAUsuario) = UPPER(?)";

  const CONSULTAR_USUARIO_POR_PREGSECRETA_APROX = "SELECT * FROM Usuario WHERE UPPER(PREGSECRETAUsuario) LIKE UPPER(?) ORDER BY PREGSECRETAUsuario";

  const CONSULTAR_USUARIO_POR_RESPPREGSECRETA = "SELECT * FROM Usuario WHERE UPPER(RESPPREGSECRETAUsuario) = UPPER(?)";

  const CONSULTAR_USUARIO_POR_RESPPREGSECRETA_APROX = "SELECT * FROM Usuario WHERE UPPER(RESPPREGSECRETAUsuario) LIKE UPPER(?) ORDER BY RESPPREGSECRETAUsuario";

}
?>