<?php 
/** 
 * @file SQLEdoRegistro.php 
 *  
 * Consultas SQL de la Tabla EdoRegistro 
 * 
 * @author UNM 
 * @version V 0.1 
 * @date 08/11/2021
 *  
*/ 
class SQLEdoRegistro 
{ 
  const AGREGAR_EDOREGISTRO = "INSERT INTO EdoRegistro (IDEDOREGISTRO, NOMEDOREGISTRO, DESCEDOREGISTRO, GPOEDOREGISTRO) VALUES (?, ?, ?, ?) ";

  const ACTUALIZAR_EDOREGISTRO = "UPDATE EdoRegistro SET IDEDOREGISTRO = ?, NOMEDOREGISTRO = ?, DESCEDOREGISTRO = ?, GPOEDOREGISTRO = ? WHERE idEdoRegistro = ?";

  const ELIMINAR_EDOREGISTRO = "DELETE FROM EdoRegistro WHERE idEdoRegistro = ?";

  const CONSULTAR_EDOREGISTRO = "SELECT * FROM EdoRegistro ORDER BY IDEDOREGISTRO";

  const CONSULTAR_EDOREGISTRO_POR_IDEDOREGISTROEDOREGISTRO = "SELECT * FROM EdoRegistro WHERE IDEDOREGISTROEdoRegistro = ?";

  const CONSULTAR_EDOREGISTRO_POR_NOMEDOREGISTRO = "SELECT * FROM EdoRegistro WHERE UPPER(NOMEDOREGISTROEdoRegistro) = UPPER(?)";

  const CONSULTAR_EDOREGISTRO_POR_NOMEDOREGISTRO_APROX = "SELECT * FROM EdoRegistro WHERE UPPER(NOMEDOREGISTROEdoRegistro) LIKE UPPER(?) ORDER BY NOMEDOREGISTROEdoRegistro";

  const CONSULTAR_EDOREGISTRO_POR_DESCEDOREGISTRO = "SELECT * FROM EdoRegistro WHERE UPPER(DESCEDOREGISTROEdoRegistro) = UPPER(?)";

  const CONSULTAR_EDOREGISTRO_POR_DESCEDOREGISTRO_APROX = "SELECT * FROM EdoRegistro WHERE UPPER(DESCEDOREGISTROEdoRegistro) LIKE UPPER(?) ORDER BY DESCEDOREGISTROEdoRegistro";

  const CONSULTAR_EDOREGISTRO_POR_GPOEDOREGISTRO = "SELECT * FROM EdoRegistro WHERE GPOEDOREGISTROEdoRegistro = ?";

}
?>